version: 2

jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Setting up environment
                command: |
                    sudo apt-get update
                    sudo apt-get install -y cmake libgtest-dev npm
            - run:
                name: Installing gtest 
                command: |
                    cd /usr/src/gtest
                    sudo mkdir build && cd build
                    sudo cmake ..
                    sudo make install
            - run:
                name: Build Test
                command: |
                    cmake .
                    make all
            - run:
                name: Launch GTest
                command: |
                    src/test/tdd-exercise-test
            
workflows:
    version: 2
    workflow:
        jobs:
            - build